const ALERT_VALUES = {
    ADD: {
        SUCCESS: 'ALERT#ADD_SUCCESS',
        FAILED: 'ALERT#ADD_FAILED'
    },
    DELETE: {
        SUCCESS: 'ALERT#DELETE_SUCCESS'
    },
    UPLOADING_FILE: {
        SUCCESS: 'ALERT#UPLOAD_FILE_SUCCESS',
        FAILED: 'ALERT#UPLOAD_FILE_FAILED'
    }
};

export default ALERT_VALUES;